# Generated by Django 4.0.1 on 2022-01-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='height',
            field=models.PositiveIntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='width',
            field=models.PositiveIntegerField(max_length=4),
        ),
    ]
