# Generated by Django 4.0.1 on 2022-01-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0003_alter_picture_height_alter_picture_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='height',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='width',
            field=models.CharField(max_length=4),
        ),
    ]
