# Generated by Django 4.0.1 on 2022-01-25 13:33

from django.db import migrations, models
import upload_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0006_alter_picture_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file',
            field=models.ImageField(storage=upload_app.models.OverwriteStorage, upload_to=upload_app.models.upload_to),
        ),
    ]
